spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.data-source-properties.useSSL=false
spring.datasource.hikari.data-source-properties.allowPublicKeyRetrieval=true
spring.datasource.hikari.data-source-properties.serverTimezone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
